model:
  arch: split_resnet_mixer
  pretrained: False
  emb_dim: 512
  maxpool: 1
  out_activation: linear
  activation: relu
  split_layers: 0
  exit_reg: 10
  mixer:
    mode: algebraic
    loss_weight: 1.0
    algebraic_use_all_terms: True

training:
  optimizer:
    lr: 0.001

data:
  training:
    batch_size: 256
  testing:
    batch_size: 2048
