project: visgen
method: bayes
metric:
  name: test/acc
  goal: maximize
parameters:
  training.optimizer.lr:
    min: 1.0e-5
    max: 5.0e-4
  training.optimizer.weight_decay:
    values: [0.0, 1.0e-6, 1.0e-5, 1.0e-4]
  model.mixer.loss_weight:
    values: [0.1, 0.3, 0.5, 1.0, 2.0]

command:
  - ${env}
  - bash
  - mixer_sweep_runner.sh
  - iraven
  - orthotopic
  - sweep
